cluster:
  name: clustername
  cidrBlocks: "10.245.0.0/16"
  controlPlaneEndpoint: "host.domain.com"
  # bgpPolicyVlan node label is used in Cilium CNI BGP, if not used leave empty and it will not be set.
  bgpPolicyVlan: "vlan201"
  skipKubeProxy: true

addons:
  # Set True if you want to use the built in CSI and CPI manifests
  # Manifests not updated to latest version so i suggest install CPI and CSI manually after cluster is up
  install_vsphere_addon: false

network:
  prefix: "24"
  gateway: "192.168.1.1"
  nameserver: "192.168.1.1"
  poolStart: "192.168.1.2"
  poolEnd: "192.168.1.254"

node:
  datastore: SSD01
  template: ubuntu-2204-kube-v1.28.0
  sshAuthorizedKeys: PublicKey

vsphere:
  server: vcenter.domain.com
  serverIP: 1.2.3.4
  datacenter: Datacenter
  resourcePool: kubernetes
  insecureFlag: true
  username: username
  password: password
  thumbprint: thumbprint
  network: vcenterNetwork
  storagePolicyName: ""
  labels:
    region: region
    zone: zone

controlPlaneNodes:
  k8sVersion: 1.28.0
  vspehereMachineTemplate: ubnt2204-2cpu-4g-128
  replicas: 3

machineDeployments:
  - name: md-0
    vspehereMachineTemplate: ubnt2204-4cpu-8g-128
    k8sVersion: 1.28.0
    replicas: 2
    # Add additonal labels to nodes
    labels:
      node-role.kubernetes.io/worker: "true"

    # Add annotations to your nodes for example if you have autoscaler
    annotations:
      # cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
      # cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "0"

  - name: md-1
    vspehereMachineTemplate: ubnt2204-4cpu-8g-128
    k8sVersion: 1.28.0
    replicas: 3
    # Add additonal labels to nodes
    labels:
      node-role.kubernetes.io/worker: "true"

    # Add annotations to your nodes for example if you have autoscaler
    annotations:
      cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
      cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "0"


# Machine templates
machineTemplates:
  - name: ubnt2204-2cpu-4g-128
    cpu: 2
    memory: 4096
    diskSize: 25
    isoTemplate: ubuntu-2204-kube-v1.28.0
    vcenterDatastore: SSD01
  - name: ubnt2204-4cpu-8g-128
    cpu: 4 
    memory: 8192
    diskSize: 35
    isoTemplate: ubuntu-2204-kube-v1.28.0
    vcenterDatastore: SSD01

kubeVIP:
  image:
    repository: ghcr.io/kube-vip/kube-vip
    tag: v0.6.2
    pullPolicy: IfNotPresent

healthChecks:
  controlplane:
    name: cp-unhealthy-5m

    # maxUnhealthy prevents further remediation if the cluster is already partially unhealthy
    maxUnhealthy: 100%

    nodeStartupTimeout: 10m0s

    # Timeout for unhealthy condition when node status Ready is unknown or False. When timeout is reached node is considered unhealthy
    unhealthyTimeoutUnknown: 5m0s
    unhealthyTimeoutFalse: 5m0s

  workernodes:
    name: worker-unhealthy-5m

    # maxUnhealthy prevents further remediation if the cluster is already partially unhealthy
    maxUnhealthy: 100%

    # nodeStartupTimeout determines how long a MachineHealthCheck should wait for
    # a Node to join the cluster, before considering a Machine unhealthy.
    # Defaults to 10 minutes.
    # Set to 0 to disable the node startup timeout.
    # Disabling this timeout will prevent a Machine from being considered unhealthy when
    # the Node it created has not yet registered with the cluster. This can be useful when
    # Nodes take a long time to start up or when you only want condition based checks for
    # Machine health.
    nodeStartupTimeout: 10m0s

    # Timeout for unhealthy condition when node status Ready is unknown or False. When timeout is reached node is considered unhealthy
    unhealthyTimeoutUnknown: 5m0s
    unhealthyTimeoutFalse: 5m0s