{{- if and (ne .Values.httpRoute.internalGateway "") .Values.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    name: {{ .Values.httpRoute.internalGateway }}
    namespace: cilium
    kind: Gateway
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: home-assistant
      port: {{ .Values.service.port }}
      weight: 1	
    matches:	
      - path:	
          type: PathPrefix	
          value: /
{{- end }}
{{- if and (ne .Values.httpRoute.externalGateway "") .Values.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    name: {{ .Values.httpRoute.externalGateway }}
    namespace: cilium
    kind: Gateway
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: home-assistant
      port: {{ .Values.service.port }}
      weight: 1	
    matches:	
      - path:	
          type: PathPrefix	
          value: /
{{- end }}
{{- if .Values.addons.codeserver.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hass-code-server
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    name: {{ .Values.addons.codeserver.httpRoute.gateway }}
    namespace: cilium
    kind: Gateway	
  hostnames:
    - {{ .Values.addons.codeserver.httpRoute.hostname }}
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: hass-code-server
      port: {{ .Values.addons.codeserver.service.por }}
      weight: 1	
    matches:	
      - path:	
          type: PathPrefix	
          value: /
{{- end }}