---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
    app: home-assistant
  name: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: {{ .Values.service.type }}
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}
{{- if .Values.addons.codeserver.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
    app: home-assistant
  name: hass-code-server
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  ports:
    {{- toYaml .Values.addons.codeserver.service.ports | nindent 4 }}
{{- end }}