---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
    app: home-assistant
  name: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: {{ .Values.service.type }}
  ports:
    - port: http
      name: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
{{- if .Values.addons.codeserver.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: home-assistant
    app: home-assistant
  name: hass-code-server
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: 
  ports:
    - port: http
      name: http
      targetPort: {{ .Values.addons.codeserver.service.port }}
      protocol: TCP
{{- end }}