---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .Values.cluster.cidrBlocks }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ .Values.cluster.name }}
    namespace: {{ .Values.cluster.name }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: {{ .Values.cluster.name }}
    namespace: {{ .Values.cluster.name }}
  topology:
    class: secure-cluster
    variables:
    - name: podSecurityStandard
      value: 
        enabled: {{ default .Values.cluster.podSecurityStandard.enabled false }}
        enforce: {{ default "restricted" .Values.cluster.podSecurityStandard.enforceLevel }}