---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
spec:
  rolloutBefore:
    certificatesExpiryDays: 21
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
          admission-control-config-file: "/etc/kubernetes/kube-apiserver-admission-pss.yaml"
        extraVolumes:
          - name: admission-pss
            hostPath: /etc/kubernetes/kube-apiserver-admission-pss.yaml
            mountPath: /etc/kubernetes/kube-apiserver-admission-pss.yaml
            readOnly: true
            pathType: "File"
      controllerManager:
        extraArgs:
          cloud-provider: external
          bind-address: 0.0.0.0
      etcd:
        local:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0
    files:
    - content: |
        apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          name: kube-vip
          namespace: kube-system
        spec:
          containers:
          - args:
            - manager
            env:
            - name: cp_enable
              value: "true"
            - name: vip_interface
              value: ""
            - name: address
              value: {{ .Values.cluster.controlPlaneEndpoint }}
            - name: port
              value: "6443"
            - name: vip_arp
              value: "true"
            - name: vip_leaderelection
              value: "true"
            - name: vip_leaseduration
              value: "15"
            - name: vip_renewdeadline
              value: "10"
            - name: vip_retryperiod
              value: "2"
            image: {{ .Values.kubeVIP.image.repository }}:{{ .Values.kubeVIP.image.tag }}
            imagePullPolicy: {{ .Values.kubeVIP.image.pullPolicy }}
            name: kube-vip
            resources: {}
            securityContext:
              capabilities:
                add:
                - NET_ADMIN
                - NET_RAW
            volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
          hostAliases:
          - hostnames:
            - kubernetes
            ip: 127.0.0.1
          hostNetwork: true
          volumes:
          - hostPath:
              path: /etc/kubernetes/admin.conf
              type: FileOrCreate
            name: kubeconfig
        status: {}
      owner: root:root
      path: /etc/kubernetes/manifests/kube-vip.yaml
    - content: |
        apiVersion: apiserver.config.k8s.io/v1
        kind: AdmissionConfiguration
        plugins:
        - name: PodSecurity
          configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1{{ if semverCompare \"< v1.25\" .Values.controlPlaneNodes.k8sVersion }}beta1{{ end }}
            kind: PodSecurityConfiguration
            defaults:
              enforce: "{{ .Values.cluster.podSecurityStandard.enforce }}"
              enforce-version: "latest"
              audit: "{{ .Values.cluster.podSecurityStandard.audit }}"
              audit-version: "latest"
              warn: "{{ .Values.cluster.podSecurityStandard.warn }}"
              warn-version: "latest"
            exemptions:
              usernames: []
              runtimeClasses: []
              namespaces: [kube-system]
      owner: root:root
      path: /etc/kubernetes/kube-apiserver-admission-pss.yaml
    initConfiguration: {{ if (default .Values.cluster.skipKubeProxy false)}}
      skipPhases:
        - addon/kube-proxy {{ end }}
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
        name: {{ printf "'{{ local_hostname }}'" }}
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
        name: {{ printf "'{{ local_hostname }}'" }}
    preKubeadmCommands:
    - hostnamectl set-hostname {{ printf "'{{ ds.meta_data.hostname }}'" }}
    - echo "::1         ipv6-localhost ipv6-loopback localhost6 localhost6.localdomain6"
      >/etc/hosts
    - echo "127.0.0.1   {{ printf "{{ ds.meta_data.hostname }} {{ local_hostname }}" }} localhost
      localhost.localdomain localhost4 localhost4.localdomain4" >>/etc/hosts
    users:
    - name: capv
      sshAuthorizedKeys:
      - {{ .Values.node.sshAuthorizedKeys }}
      sudo: ALL=(ALL) NOPASSWD:ALL
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereMachineTemplate
      name: {{ .Values.cluster.name }}-{{ .Values.controlPlaneNodes.vspehereMachineTemplate }}
      namespace: {{ .Values.cluster.name }}
  replicas: {{ .Values.controlPlaneNodes.replicas }}
  version: v{{ .Values.controlPlaneNodes.k8sVersion }}