{{- range .Values.machineDeployments }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ $.Values.cluster.name }}
  name: {{ $.Values.cluster.name }}-{{ .name}}
  namespace: {{ $.Values.cluster.name }}
spec:
  clusterName: {{ $.Values.cluster.name }}
  replicas: {{ template "worker.replicas" . }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ $.Values.cluster.name }}
      cluster.x-k8s.io/deployment-name: {{ $.Values.cluster.name }}-{{ .name}}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ $.Values.cluster.name }}
        cluster.x-k8s.io/deployment-name: {{ $.Values.cluster.name }}-{{ .name}}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $.Values.cluster.name }}-kubeadmconfig
      clusterName: {{ $.Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: {{ $.Values.cluster.name }}-{{ .vspehereMachineTemplate}}
      version: v{{ .k8sVersion }}
{{ end }}