{{- range .Values.machineDeployments }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ $.Values.cluster.name }}-node-unhealthy-5m
spec:
  clusterName: {{ $.Values.cluster.name }}
  maxUnhealthy: {{ $.Values.healthChecks.workernodes.maxUnhealthy }}
  nodeStartupTimeout: {{ $.Values.healthChecks.workernodes.nodeStartupTimeout }}
  selector:
    matchLabels:
      # nodepool: vsphere-quickstart-md-0
      cluster.x-k8s.io/deployment-name: {{ $.Values.cluster.name }}-{{ .name }}
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: {{ $.Values.healthChecks.workernodes.unhealthyTimeoutUnknown }}
  - type: Ready
    status: "False"
    timeout: {{ $.Values.healthChecks.workernodes.unhealthyTimeoutFalse }}
{{ end }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ .Values.cluster.name }}-{{ .Values.healthChecks.controlplane.name }}
spec:
  clusterName: {{ .Values.cluster.name }}
  maxUnhealthy: {{ .Values.healthChecks.controlplane.maxUnhealthy }}
  nodeStartupTimeout: {{ .Values.healthChecks.controlplane.nodeStartupTimeout }}
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ""
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: {{ .Values.healthChecks.controlplane.unhealthyTimeoutUnknown }}
    - type: Ready
      status: "False"
      timeout: {{ .Values.healthChecks.controlplane.unhealthyTimeoutFalse }}
