{{ if .Values.addons.install_vsphere_addon }}
  {{ default "false" .Values.addons.install_vsphere_addon }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-csi-controller
  namespace: {{ .Values.cluster.name }}
stringData:
  data: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: vsphere-csi-controller
      namespace: kube-system
type: addons.cluster.x-k8s.io/resource-set
{{ end }}