{{ if .Values.addons.install_vsphere_addon }}
  {{ default "false" .Values.addons.install_vsphere_addon }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-controller-manager
  namespace: {{ .Values.cluster.name }}
stringData:
  data: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        component: cloud-controller-manager
        vsphere-cpi-infra: service-account
      name: cloud-controller-manager
      namespace: kube-system
type: addons.cluster.x-k8s.io/resource-set
{{ end }}