{{ if .Values.addons.install_vsphere_addon }}
  {{ default "false" .Values.addons.install_vsphere_addon }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-vsphere-credentials
  namespace: {{ .Values.cluster.name }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      labels:
        component: cloud-controller-manager
        vsphere-cpi-infra: secret
      name: cloud-provider-vsphere-credentials
      namespace: kube-system
    stringData:
      {{ .Values.vsphere.server }}.password: {{ .Values.vsphere.password }}
      {{ .Values.vsphere.server }}.username: {{ .Values.vsphere.username }}
    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
{{ end }}