{{ if (default .Values.addons.install_vsphere_addon false)}}
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-vsphere-config
  namespace: {{ .Values.cluster.name }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: csi-vsphere-config
      namespace: kube-system
    stringData:
      csi-vsphere.conf: |+
        [Global]
        cluster-id = "{{ .Values.cluster.name }}/{{ .Values.cluster.name }}"

        [VirtualCenter "vcenter.threshold.se"]
        user = "{{ .Values.vsphere.username }}"
        password = "{{ .Values.vsphere.password }}"
        insecure-flag = {{ .Values.vsphere.insecureFlag }}
        datacenters = "{{ .Values.vsphere.datacenter }}"

        [Network]
        public-network = "{{ .Values.vsphere.network }}"

    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
{{ end }}